config/routes.rb
Rails.application.routes.draw do

  root 'informations#root'

  # 情報提供用のルーティング
  get 'informations', to: 'informations#home'

  get 'informations/map', to: 'informations#map', as: 'map_mode'

  get 'informations/image', to: 'informations#image', as: 'image_mode'

  get 'informations/control', to: 'informations#control', as: 'control_mode'

  get 'informations/help', to: 'informations#help', as: 'help'

  # ブラウザ用のRobotsコントローラのルーティング
  resources :robots do
    collection do
      delete 'destroy_multiple'
    end
  end

  # ブラウザ用のMapsコントローラのルーティング
  resources :maps do
    collection do
      delete 'destroy_multiple'
    end
    resources :nodes
  end

  resources :images do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :tasks do
    collection do
      delete 'destroy_multiple'
    end
  end

  # apiコントローラのルーティング
  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :robots
      resources :maps do
        resources :nodes do
          collection do
            get ':id/nexts', to: 'nodes#show_next'
            get 'only_usable', to: 'nodes#show_usable'
          end
        end
        # collection do
        #   get '?map_name=', to: '#show_map_id'
        # end
      end
      resources :tasks
      resources :images

    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :map
  belongs_to :node
  belongs_to :robot
end

app/controllers/api/v1/tasks_controller.rb
# app/controllers/api/v1/tasks_controller.rb
module Api
  module V1
    class TasksController < ApplicationController
      before_action :set_task, only: [:show, :edit, :update, :destroy]
      protect_from_forgery :except => [:create, :update]

      # GET /tasks
      # GET /tasks.json
      def index
        # クエリパラメータによる指定があった場合
        unless params[:robot_id].blank? && params[:map_id].blank?
          # ロボットIDが指定されたタスクのみを返す場合
          unless params[:robot_id].blank?
            robot = Robot.find(params[:robot_id])
              unless robot.nil?
                @tasks = robot.tasks
              end
          else
            # マップIDが指定されたタスクのみを返す場合
            map = Map.find(params[:map_id])
            unless map.nil?
              @tasks = map.tasks
            end
          end
        else
          @tasks = Task.all
        end
      end

      # GET /tasks/1
      # GET /tasks/1.json
      def show
      end

      # GET /tasks/new
      def new
        @task = Task.new
      end

      # GET /tasks/1/edit
      def edit
      end

      # POST /tasks
      # POST /tasks.json
      def create
        @task = Task.new(task_params)

        respond_to do |format|
          if @task.save
            format.html { redirect_to @task, notice: 'Task was successfully created.' }
            format.json { render :show, status: :created, location: @task }
          else
            format.html { render :new }
            format.json { render json: @task.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /tasks/1
      # PATCH/PUT /tasks/1.json
      def update
        respond_to do |format|
          if @task.update(task_params)
            format.html { redirect_to @task, notice: 'Task was successfully updated.' }
            format.json { render :show, status: :ok, location: @task }
          else
            format.html { render :edit }
            format.json { render json: @task.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /tasks/1
      # DELETE /tasks/1.json
      def destroy
        @task.destroy
        respond_to do |format|
          format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_task
          @task = Task.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def task_params
          response = params.require(:task).permit(:task_type, :map_id, :map_name, :node_id, :node_name, :robot_id, :trial)
          # タスクタイプによる処理
          response = processing_task_type(response)
          # マップ名で登録
          response = trans_map_name2id(response)
          # ノード名で登録
          trans_node_name2id(response)
        end

        def trans_map_name2id(params)
          # マップ名で登録
          unless params[:map_name].nil?
            unless Map.find_by(name: params[:map_name]).nil?
              params[:map_id] = Map.find_by(name: params[:map_name]).id
            end
            params.delete(:map_name)
          end
          params
        end

        def trans_node_name2id(params)
          # ノード名で登録
          unless params[:node_name].nil?
            unless Node.find_by(name: params[:node_name]).nil?
              params[:node_id] = Node.find_by(name: params[:node_name]).id
            end
            params.delete(:node_name)
          end
          params
        end

        def processing_task_type(params)
          # task_type依存の処理
          # 定時連絡は解決すべきタスクに含めない
          if params[:task_type] == "Ordinary Contact"
            params[:is_resolved] = true
          end
          params
        end
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_trial
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # まとめて消す
  def destroy_multiple
    Task.destroy(params[:tasks])

    respond_to do |format|
      format.html { redirect_to tasks_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:task_type, :map_id, :node_id, :robot_id, :is_resolved)
    end


    def set_trial
      unless params[:trial].blank?
        @trial = params[:trial]
      else
        @trial = "all"
      end
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task_type %>
    <%= form.text_field :task_type, id: :task_task_type %>
  </div>

  <div class="field">
    <%= form.label :map_id %>
    <%= form.text_field :map_id, id: :task_map_id %>
  </div>

  <div class="field">
    <%= form.label :node_id %>
    <%= form.text_field :node_id, id: :task_node_id %>
  </div>

  <div class="field">
    <%= form.label :robot_id %>
    <%= form.text_field :robot_id, id: :task_robot_id %>
  </div>

  <div class="field">
    <%= form.label :is_resolved %>
    <%= form.text_field :is_resolved, id: :task_is_resolved %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<%= form_tag destroy_multiple_tasks_path, method: :delete do %>
<table>
  <thead>
    <tr>
      <th><input type="checkbox" id="all" /> Check all</th>
      <th>Task type</th>
      <th>Map</th>
      <th>Node</th>
      <th>Robot</th>
      <th>is Resolved</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= check_box_tag "tasks[]", task.id %></td>
        <td><%= task.task_type %></td>
        <% unless task.map.nil? %>
        <td><%= task.map.id %></td>
        <% else %>
        <td><%= %></td>
        <% end %>
        <% unless task.node.nil? %>
        <td><%= task.node.id %></td>
        <% else %>
        <td><%= %></td>
        <% end %>
        <% unless task.robot.nil? %>
        <td><%= task.robot.id %></td>
        <% else %>
        <td><%= %></td>
        <% end %>
        <td><%= task.is_resolved %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= submit_tag "Delete selected" %>
<% end %>
<br>

<%= link_to 'New Task', new_task_path %>

<script type="text/javascript">
$('#all').on('change', function() {
    $('input[type=checkbox').prop('checked', this.checked);
});
</script>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task type:</strong>
  <%= @task.task_type %>
</p>

<p>
  <strong>Map:</strong>
  <%= @task.map %>
</p>

<p>
  <strong>Node:</strong>
  <%= @task.node %>
</p>

<p>
  <strong>Robot:</strong>
  <%= @task.robot %>
</p>

<p>
  <strong>is Resolved:</strong>
  <%= @task.is_resolved %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>