config/routes.rb
Rails.application.routes.draw do

  root 'informations#root'

  # 情報提供用のルーティング
  get 'informations', to: 'informations#home'

  get 'informations/map', to: 'informations#map', as: 'map_mode'

  get 'informations/image', to: 'informations#image', as: 'image_mode'

  get 'informations/control', to: 'informations#control', as: 'control_mode'

  get 'informations/help', to: 'informations#help', as: 'help'

  # ブラウザ用のRobotsコントローラのルーティング
  resources :robots do
    collection do
      delete 'destroy_multiple'
    end
  end

  # ブラウザ用のMapsコントローラのルーティング
  resources :maps do
    collection do
      delete 'destroy_multiple'
    end
    resources :nodes
  end

  resources :images do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :tasks do
    collection do
      delete 'destroy_multiple'
    end
  end

  # apiコントローラのルーティング
  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :robots
      resources :maps do
        resources :nodes do
          collection do
            get ':id/nexts', to: 'nodes#show_next'
            get 'only_usable', to: 'nodes#show_usable'
          end
        end
        # collection do
        #   get '?map_name=', to: '#show_map_id'
        # end
      end
      resources :tasks
      resources :images

    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/map.rb
class Map < ApplicationRecord
  has_many :nodes, dependent: :destroy
  has_many :robots
  has_many :tasks
end

app/controllers/api/v1/maps_controller.rb
# app/controllers/api/v1/maps_controller.rb
module Api
  module V1
    class MapsController < ApplicationController
      before_action :set_map, only: [:show, :edit, :update, :destroy]

      # GET /maps
      # GET /maps.json
      def index
        unless params[:map_name].blank?
          # クエリパラメータでマップ名を指定された場合
          map = Map.find_by(name: params[:map_name])
          render :json => {map_id: map.id}
        else
          @maps = Map.all
        end
      end

      # GET /maps/1
      # GET /maps/1.json
      def show
      end

      # GET /maps/new
      def new
        @map = Map.new
      end

      # GET /maps/1/edit
      def edit
      end

      # POST /maps
      # POST /maps.json
      def create
        @map = Map.new(map_params)

        respond_to do |format|
          if @map.save
            format.html { redirect_to @map, notice: 'Map was successfully created.' }
            format.json { render :show, status: :created, location: @map }
          else
            format.html { render :new }
            format.json { render json: @map.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /maps/1
      # PATCH/PUT /maps/1.json
      def update
        respond_to do |format|
          if @map.update(map_params)
            format.html { redirect_to @map, notice: 'Map was successfully updated.' }
            format.json { render :show, status: :ok, location: @map }
          else
            format.html { render :edit }
            format.json { render json: @map.errors, status: :unprocessable_entity }
          end
        end
      end


      # DELETE /maps/1
      # DELETE /maps/1.json
      def destroy
        @map.destroy
        respond_to do |format|
          format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_map
          @map = Map.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def map_params
          params.require(:map).permit(:name, :map_file, :last_update, :map_id, :node_id)
        end
    end
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_trial
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # まとめて消す
  def destroy_multiple
    Map.destroy(params[:maps])

    respond_to do |format|
      format.html { redirect_to maps_path }
      format.json { head :no_content }
    end
  end

  # リンクを取得する
  def links
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:name, :map_file, :last_update, :map_id, :node_id)
    end


    def set_trial
      unless params[:trial].blank?
        @trial = params[:trial]
      else
        @trial = "all"
      end
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.erb
<%= form_with(model: map, local: true) do |form| %>
  <% if map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :map_name %>
  </div>

  <div class="field">
    <%= form.label :map_file %>
    <%= form.text_field :map_file, id: :map_map_file %>
  </div>

  <div class="field">
    <%= form.label :last_update %>
    <%= form.datetime_select :last_update, id: :map_last_update %>
  </div>

  <div class="field">
    <%= form.label :map_id %>
    <%= form.text_field :map_id, id: :map_map_id %>
  </div>

  <div class="field">
    <%= form.label :node_id %>
    <%= form.text_field :node_id, id: :map_node_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Maps</h1>

<%= form_tag destroy_multiple_maps_path, method: :delete do %>
<table>
  <thead>
    <tr>
      <th><input type="checkbox" id="all" /> Check all</th>
      <th>Name</th>
      <th>Map file</th>
      <th>Last update</th>
      <!-- <th>Map</th>
      <th>Node</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each do |map| %>
      <tr>
        <td><%= check_box_tag "maps[]", map.id %></td>
        <td><%= map.name %></td>
        <td><%= map.map_file %></td>
        <td><%= map.last_update %></td>
        <td><%= link_to 'Show', map %></td>
        <td><%= link_to 'Edit', edit_map_path(map) %></td>
        <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= submit_tag "Delete selected" %>
<% end %>
<br>

<%= link_to 'New Map', new_map_path %>

<script type="text/javascript">
$('#all').on('change', function() {
    $('input[type=checkbox').prop('checked', this.checked);
});
</script>

app/views/maps/new.html.erb
<h1>New Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @map.name %>
</p>

<p>
  <strong>Map file:</strong>
  <%= @map.map_file %>
</p>

<p>
  <strong>Last update:</strong>
  <%= @map.last_update %>
</p>

<p><strong>nodes</strong></p>
<% @map.nodes&.each do |node| %>
  <p>
    <td>
      <%= node.name %>
      <%= node.x %>
      <%= node.y %>
      <%= node.usable %>
      <%= (node.type_a_next_nodes + node.type_b_next_nodes).each do |next_node|%>
      <% end %>
    </td>
  </p>
<% end %>


<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>