config/routes.rb
Rails.application.routes.draw do

  root 'informations#root'

  # 情報提供用のルーティング
  get 'informations', to: 'informations#home'

  get 'informations/map', to: 'informations#map', as: 'map_mode'

  get 'informations/image', to: 'informations#image', as: 'image_mode'

  get 'informations/control', to: 'informations#control', as: 'control_mode'

  get 'informations/help', to: 'informations#help', as: 'help'

  # ブラウザ用のRobotsコントローラのルーティング
  resources :robots do
    collection do
      delete 'destroy_multiple'
    end
  end

  # ブラウザ用のMapsコントローラのルーティング
  resources :maps do
    collection do
      delete 'destroy_multiple'
    end
    resources :nodes
  end

  resources :images do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :tasks do
    collection do
      delete 'destroy_multiple'
    end
  end

  # apiコントローラのルーティング
  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :robots
      resources :maps do
        resources :nodes do
          collection do
            get ':id/nexts', to: 'nodes#show_next'
            get 'only_usable', to: 'nodes#show_usable'
          end
        end
        # collection do
        #   get '?map_name=', to: '#show_map_id'
        # end
      end
      resources :tasks
      resources :images

    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  before_action :set_trial
  before_action :set_floor
  before_action :select_images, only: [:map, :image]

  def root
  end

  def home
  end

  # GET /informations/complex
  def map
    unless params[:node].blank?
      node_id = params[:node]
    else
      node_id = @map.nodes.first.id
    end

    @node = Node.find(node_id)
    if @node.nil?
      @node = @map.nodes.first
    end

    @nodes = @map.nodes

    @images = @images_base.where(node_id: @node.id)
    @images_sub = []
    (@node.type_a_next_nodes + @node.type_b_next_nodes).each do |next_node|
    @images_sub.push(@images_base.where(node_id: next_node.id))
    end
  end

  def control
  end

  # GET /informations/image
  # ソートに使えるカラム(SQLインジェクション対応)
  VALID_SORT_COLUMNS = %w(begin_node node_id created_at)
  def image
    unless params[:sort].blank?
      sort = params[:sort] if VALID_SORT_COLUMNS.include?(params[:sort])
      @images_base = @images_base.order(sort)
      if params[:sort_option] == "down"
        @images_base = @images_base.reverse_order
      end
    end
    @images = @images_base.page(params[:page]).per(25)
  end

  def help
  end

  private
    def set_trial
      unless params[:trial].blank?
        @trial = params[:trial]
      else
        @trial = "all"
      end
    end

    def set_floor
      unless params[:floor].blank?
        @floor_id = params[:floor]
      else
        @floor_id = "1"
      end

      if Map.exists?(@floor_id)
        @map = Map.find(@floor_id)
      else
        @map = Map.first
        @floor_id = @map.id.to_s
      end
    end

    def select_images
      if @trial == "all"
        @images_base = Image
      else
        @images_base = Image.where(trial: @trial)
      end
    end
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/views/informations/control.html.erb
<% provide(:title, 'Control Mode') %>
<h1 id="-">準備中</h1>
<hr>
<h2 id="-">制御モードは準備中です</h2>

app/views/informations/help.html.erb
<% provide(:title, 'Help') %>
<% provide(:nav_title, 'ヘルプ') %>
<h1>利用方法</h1>
<hr>
<h2>ナビゲーションバーの各ページについて</h2>
<ol>
<%= image_tag 'navbar-sample.png', :class => 'sample'%>
<li>全体図とは？<br>名古屋工業大学の全体図から情報を見たい建物を選ぶページです。</li>
<li>地図モードとは？<br>あるフロアについて、屋内マップとノードを元に情報を閲覧するページです。<br>情報を容易に把握することを重視したモードです。</li>
<li>一覧モードとは？<br>あるフロアについて、列挙された情報を閲覧するページです。<br>情報を網羅的に把握することを重視したモードです。</li>
<!-- <li>制御モードとは？<br>ロボットを制御するページです。<br>あるフロアについて、特定のエリアにロボットを誘導し情報を収集します。</li> -->
<li>ヘルプとは？<br>このページです。</li>
<li>管理Serverとは？<br>サーバーに蓄積された情報を直接閲覧するためのページです。</li>
</ol>
<hr>
<h2>全体図の使い方</h2>
<ol>
<li>ナビゲーションバーから"全体図"をクリック(タッチ)してください。</li>
<li>情報を見たい建物を囲う赤枠内をクリック(タッチ)してください。</li>
<%= image_tag 'map-sample.png', :class => 'sample' %>
<li>クリック(タッチ)した建物の情報閲覧ページ(地図モード)に移行します。</li>
</ol>
<hr>
<h2>地図モードの使い方</h2>
<ol>
<li>ナビゲーションバーから"地図Mode"をクリック(タッチ)してください。<br>
もしくは、全体図から建物をクリック(タッチ)してください。</li>
<li>地図モードでは注目しているフロアの情報がフロアマップとともに表示されます。<br>
注目しているフロアはナビゲーションバーに表示されます。
<%= image_tag 'floor-name-sample.png', :class => 'sample' %></li>
<li>画面下部にある屋内マップから、情報を見たいノードをクリック(タッチ)してください。
<%= image_tag 'node-sample.png', :class => 'sample' %><br></li>
<li>ノードをクリック(タッチ)すると、クリック(タッチ)したノードとその周りのノードが円で囲われます。
<br>ノードを囲う円の色と同じ色で囲われた画像がノード付近の画像です。
<%= image_tag 'selected-node-sample.png', :class => 'sample' %></li>
<li>注目したい画像があった場合、その画像をクリック(タッチ)してください。<br>新しいタブで詳細情報(より解像度の大きな画像など)に移行します。</li>
<li>紫のトゲで囲われたノードがある場合があります。
<br>そのノードの付近には要救助者がいる可能性が高いです。
<%= image_tag 'warning-node-sample.png', :class => 'sample' %></li>
</ol>
<hr>
<h2>一覧モードの使い方</h2>
<ol>
<li>ナビゲーションバーから"一覧Mode"をクリック(タッチ)してください。<br>
<li>一覧モードでは注目しているフロアの画像が表形式で表示されます。<br>
出発Node・目標Nodeはそれぞれロボットがその画像を取った際の、出発地点と目標地点です。</li>
<%= image_tag 'image-viewer-sample.png', :class => 'sample' %>
<li>情報を並べ替えたい場合(出発ノード・目標ノード・投稿時間)のところにある▲▼を選択してください。<br>それぞれ情報が昇順・降順に並べ替えられます。</li>
<li>情報が25個以上の場合青いバーが表示されます。続きを見る場合にバーを利用してください。</li>
<%= image_tag 'pagination-sample.png', :class => 'sample' %>
<li>注目したい画像があった場合、地図モード同様に画像もしくはDetailsをクリック(タッチ)してください。<br>新しいタブで詳細情報(より解像度の大きな画像など)に移行します。</li>
<!-- </ol>
<h2>制御モードの使い方</h2>
<p>準備中です。</p> -->

app/views/informations/home.html.erb
<% provide(:title, 'Home') %>
<% provide(:nav_title, '名古屋工業大学全体図') %>
<div class="nitech_map">
  <%= image_tag 'nitech_map.jpg', :class => 'resize nitech' %>
  <a href='#' onclick='building_clicked(2);'>
    <%= image_tag 'square.png', :size => "75x50", :class => 'nitech_2' %>
  </a>
</div>
<script type="text/javascript">
  function building_clicked(n) {
    console.log("clicked");
    location.href = "<%= map_mode_path %>?trial=<%= @trial %>&floor=" + (n - 1)
  }
</script>

app/views/informations/image.html.erb
<p id="notice"><%= notice %></p>

<% provide(:title, 'Image Mode') %>
<% provide(:nav_title, @map.name) %>
<!-- <h1>Images</h1> -->
<%= paginate @images %>
<%= page_entries_info @images %>
<table class="table table-bordered">
  <thead>
    <tr>
      <th class="text-center">画像</th>
      <th class="text-center">出発Node<%= link_to "▲", image_mode_path(trial: @trial, floor: @floor_id, sort: "begin_node", sort_option: "up") %><%= link_to "▼", image_mode_path(trial: @trial, floor: @floor_id, sort: "begin_node", sort_option: "down") %></th>
      <th class="text-center">目標Node<%= link_to "▲", image_mode_path(trial: @trial, floor: @floor_id, sort: "node_id", sort_option: "up") %><%= link_to "▼", image_mode_path(trial: @trial, floor: @floor_id, sort: "node_id", sort_option: "down") %></th>
      <!-- <th>Comment</th> -->
      <!-- <th>Trial</th> -->
      <th class="text-center">投稿時間<%= link_to "▲", image_mode_path(trial: @trial, floor: @floor_id, sort: "created_at", sort_option: "up") %><%= link_to "▼", image_mode_path(trial: @trial, floor: @floor_id, sort: "created_at", sort_option: "down") %></th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td class="text-center">
          <% if image.image? %>
            <div class="thumbnail">
              <%= link_to image_tag(image.image.thumb.url), image, target: "_new" %>
            </div>
          <% end %>
        </td>
        <td class="text-center">Node<%= image.begin_node %></td>
        <% unless image.node.nil? %>
        <td class="text-center"><%= image.node.name %></td>
        <% else %>
        <td><%= %></td>
        <% end %>
        <!-- <td><%= image.comment %></td> -->
        <!-- <td><%= image.trial %></td> -->
        <td class="text-center"><%= image.created_at.strftime('%Y/%m/%d %H:%M') %></td>
        <td class="text-center"><%= link_to 'Details', image, target: "_new"%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= paginate @images %>
<%= page_entries_info @images %>
<br>

app/views/informations/map.html.erb
<p id="notice"><%= notice %></p>

<% provide(:title, 'Map Mode') %>
<% provide(:nav_title, @map.name) %>
<div class="all">
  <div class="container area1">
      <% @images.each do |image| %>
        <% if image.image? %>
          <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-2">
            <p class="resizeimage">
              <div class="thumbnail target">
                <%= link_to image_tag(image.image.thumb.url), image, target: "_new" %>
              </div>
            </p>
          </div>
        <% end %>
      <% end %>
      <% @images_sub.each_with_index do |subs,count| %>
        <% subs.each do |image| %>
          <% if image.image? %>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 col-xl-2">
              <p class="resizeimage">
                <div class="thumbnail sub<%= count %>">
                  <%= link_to image_tag(image.image.thumb.url), image, target: "_new" %>
                </div>
              </p>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <div class="area2">
  <!-- 複数マップ対応の際に要修正 -->
    <%= image_tag @map.name+'.png', :class => 'map resize' %>
    <% @nodes.each_with_index do |node,count| %>
      <a href='#' onclick='node_clicked(<%= node.id %>);'>
        <%= image_tag 'position_icon.png', :size => "35x35", :class => 'node node'+(count+1).to_s+' black' %>
        <%= image_tag 'position_icon_red.png', :size => "35x35", :class => 'node node'+(count+1).to_s+' red' %>
      </a>
      <% unless node.usable %>
        <!-- <span class="tooltip"> -->
          <%= image_tag 'warning.png', :size => "60x60", :class => 'node node'+(count+1).to_s %>
        <!-- </span> -->
      <% end %>
    <% end %>
    <%= image_tag 'circle.png', :size => "50x50", :class => 'node node'+ @node.id.to_s%>
    <% (@node.type_a_next_nodes + @node.type_b_next_nodes).each_with_index do |next_node,count| %>
      <%= image_tag ('circle_' + count.to_s + '.png'), :size => "50x50", :class => 'node node'+ next_node.id.to_s %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  function node_clicked(n) {
    console.log("clicked");
    location.href = "<%= map_mode_path %>?trial=<%= @trial %>&floor=<%= @floor_id %>&node=" + n;
  }
</script>

app/views/informations/root.html.erb
<h1>ManagementServer</h1>
<p>DB集積情報の閲覧ページ</p>
<hr>
<h2><%= link_to "Robots",   robots_path(trial: @trial, floor: @floor_id) %></h2>
<h2><%= link_to "Maps",   maps_path(trial: @trial, floor: @floor_id) %></h2>
<h2><%= link_to "Tasks",   tasks_path(trial: @trial, floor: @floor_id) %></h2>
<h2><%= link_to "Informations",   informations_path(trial: @trial, floor: @floor_id) %></h2>
<h2><%= link_to "Images",   images_path(trial: @trial, floor: @floor_id) %></h2>