config/routes.rb
Rails.application.routes.draw do

  root 'informations#root'

  # 情報提供用のルーティング
  get 'informations', to: 'informations#home'

  get 'informations/map', to: 'informations#map', as: 'map_mode'

  get 'informations/image', to: 'informations#image', as: 'image_mode'

  get 'informations/control', to: 'informations#control', as: 'control_mode'

  get 'informations/help', to: 'informations#help', as: 'help'

  # ブラウザ用のRobotsコントローラのルーティング
  resources :robots do
    collection do
      delete 'destroy_multiple'
    end
  end

  # ブラウザ用のMapsコントローラのルーティング
  resources :maps do
    collection do
      delete 'destroy_multiple'
    end
    resources :nodes
  end

  resources :images do
    collection do
      delete 'destroy_multiple'
    end
  end

  resources :tasks do
    collection do
      delete 'destroy_multiple'
    end
  end

  # apiコントローラのルーティング
  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :robots
      resources :maps do
        resources :nodes do
          collection do
            get ':id/nexts', to: 'nodes#show_next'
            get 'only_usable', to: 'nodes#show_usable'
          end
        end
        # collection do
        #   get '?map_name=', to: '#show_map_id'
        # end
      end
      resources :tasks
      resources :images

    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav>
          <!-- <div class="container-fluid"> -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <%= link_to navbar_title(yield(:nav_title)), root_path(trial: @trial, floor: @floor_id), id: "logo" %>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                <li class="nav-item"><%= link_to "全体図",   informations_path(trial: @trial, floor: @floor_id) %></li>
                <li class="nav-item"><%= link_to "地図Mode", map_mode_path(trial: @trial, floor: @floor_id) %></li>
                <li class="nav-item"><%= link_to "一覧Mode", image_mode_path(trial: @trial, floor: @floor_id) %></li>
                <!-- <li class="nav-item"><%= link_to "制御Mode", control_mode_path(trial: @trial, floor: @floor_id) %></li> -->
                <li class="nav-item"><%= link_to "Help", help_path(trial: @trial, floor: @floor_id) %></li>
              </ul>
            </div><!-- /.navbar-collapse -->
          <!-- </div> -->
        </nav>
      </div>
    </header>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/application_tmp.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManagementServer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>